"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import Maintenance, MaintenanceCreate, MaintenanceUpdate
from .store import store

app = FastAPI(
    title="Fleet Inspection And Maintenance API",
    version="0.1.0",
    description="REST API for Fleet Inspection And Maintenance. Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "maintenances", "description": "Maintenances managed by this service."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/maintenances", response_model=List[Maintenance], tags=["maintenances"])
def list_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/maintenances", response_model=Maintenance, status_code=201, tags=["maintenances"])
def create_item(body: MaintenanceCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/maintenances/{item_id}", response_model=Maintenance, tags=["maintenances"])
def get_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Maintenance not found")
    return item


@app.patch("/api/maintenances/{item_id}", response_model=Maintenance, tags=["maintenances"])
def update_item(item_id: int, body: MaintenanceUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="Maintenance not found")
    return item


@app.delete("/api/maintenances/{item_id}", status_code=204, tags=["maintenances"])
def delete_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="Maintenance not found")
